services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: tyre_user
      POSTGRES_PASSWORD: tyre_pass
      POSTGRES_DB: tyre_db
    ports:
      - "5432:5432"
    volumes:
      - tyre_data:/var/lib/postgresql/data

  tyres_service:
    build: ./backend/tyres_service
    container_name: tyres_service
    ports:
      - "8001:8000"
    environment:
      POSTGRES_USER: tyre_user
      POSTGRES_PASSWORD: tyre_pass
      POSTGRES_DB: tyre_db
      POSTGRES_HOST: postgres
    depends_on:
      - postgres

  orders_service:
    build: ./backend/orders_service
    container_name: orders_service
    ports:
      - "8002:8000"
    depends_on:
      - postgres

volumes:
  tyre_data:


  #users_service:
    #build: ./backend/users_service
    #container_name: users_service
    #ports:
    #  - "8003:8000"

  #notifications_service:
    #build: ./backend/notifications_service
    #container_name: notifications_service
    #ports:
    #  - "8004:8000"