services:
  tyres_service:
    build: ./backend/tyres_service
    container_name: tyres_service
    ports:
      - "8001:8000"

  orders_service:
    build: ./backend/orders_service
    container_name: orders_service
    ports:
      - "8002:8000"

  #users_service:
    #build: ./backend/users_service
    #container_name: users_service
    #ports:
    #  - "8003:8000"

  #notifications_service:
    #build: ./backend/notifications_service
    #container_name: notifications_service
    #ports:
    #  - "8004:8000"